[phases.setup]
aptPkgs = [
  "libcairo2-dev",
  "libpango1.0-dev",
  "libgdk-pixbuf2.0-dev",
  "libffi-dev",
  "shared-mime-info",
  "pkg-config",
  "libxcb1-dev",
  "libxcb-render0-dev",
  "libxcb-shm0-dev",
  "libxcb-xfixes0-dev"
]
