# Generated by Django 5.0.1 on 2026-03-16 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер накладной')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждена'), ('received', 'Получена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_updated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.delivery', verbose_name='Поставка')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
            },
        ),
    ]
